artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_dir: artifacts/data_ingestion/raw_data
  source_path: data/data_from_db_as_csv/production
  
data_validation:
  root_dir: artifacts/data_validation
  report_file_path: artifacts/data_validation/report.yaml
  report_page_file_path: artifacts/data_validation/report.html

data_transformation:
  root_dir: artifacts/data_transformation
  training_data: artifacts/data_transformation/training_data.csv